# Generated by Django 3.2.5 on 2021-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_run_created_by'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized_programs',
            field=models.ManyToManyField(blank=True, related_name='authorized_users', to='files.Program'),
        ),
    ]
