# Generated by Django 3.2.5 on 2021-09-10 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_program_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='accounts.user'),
            preserve_default=False,
        ),
    ]
